// Package entitymeta documents the contract between entity structs and cmd/entitygen.
//
// Struct tags (field resolution order):
//   1. db:"column_name" — canonical PostgreSQL column name.
//   2. If db is empty, bson:"field_name" — used so Mongo-oriented models can share structs; the column name is the tag value.
//   3. If both are empty, the field is skipped (not persisted).
//
// Table name is not inferred from the struct name. Pass -table to entitygen (or future //entitygen:table comment).
//
// Primary key: the column named "id" (TEXT) is treated as the primary key unless -pk names another column.
// The matching Go field must be string and implement ID() via embedding or method on the entity type.
//
// Version: a field with db/bson tag "version" of type int64 or *int64 participates in optimistic concurrency.
//
// Generated artifacts:
//   - <entity>_store.go — RowStore implementation (explicit Scan/Args, no reflection in query paths).
//   - migrations/<seq>_<table>_init.up.sql — goose-formatted additive DDL (CREATE TABLE IF NOT EXISTS, REPLICA IDENTITY FULL).
//
// Additive policy: entitygen emits IF NOT EXISTS for tables and columns; destructive drops are not generated by default.
package entitymeta

// ColumnKind classifies a mapped field for SQL type selection.
type ColumnKind int

const (
	KindString ColumnKind = iota
	KindInt64
	KindBool
)
