// Code generated by github.com/dhlab-tech/go-inmemory-platform/cmd/entitygen. DO NOT EDIT.

package testwidget

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/dhlab-tech/go-inmemory-platform/pkg/postgres"
	"github.com/jackc/pglogrepl"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

const (
	_widgetSQLCols = "\"id\", \"title\", \"version\", \"deleted\""
	_widgetOrderPK = "\"id\""
	_widgetUpdateSet = "\"title\" = $2, \"version\" = $3, \"deleted\" = $4"
)

// WidgetStore is a generated [postgres.RowStore] for Widget (typed columns; no reflection on query paths).
type WidgetStore struct {
	pool   *pgxpool.Pool
	schema string
	table  string
}

// NewWidgetStore constructs a store. table is the logical table name (same as entity.Table in inmemory).
func NewWidgetStore(pool *pgxpool.Pool, schema, table string) *WidgetStore {
	return &WidgetStore{pool: pool, schema: schema, table: table}
}

func (s *WidgetStore) qualified() string {
	return postgres.QualifiedTable(s.schema, s.table)
}

func scanWidgetRow(row interface{ Scan(dest ...any) error }) (*Widget, error) {
	var v Widget
	if err := row.Scan(&v.IDVal, &v.Title, &v.Ver, &v.Del); err != nil {
		return nil, err
	}
	return &v, nil
}

func (s *WidgetStore) All(ctx context.Context) ([]*Widget, error) {
	q := fmt.Sprintf("SELECT "+_widgetSQLCols+" FROM %s ORDER BY "+_widgetOrderPK, s.qualified())
	rows, err := s.pool.Query(ctx, q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*Widget
	for rows.Next() {
		v, err := scanWidgetRow(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

func (s *WidgetStore) FindWithFilter(ctx context.Context, whereSQL string) ([]*Widget, error) {
	whereSQL = strings.TrimSpace(whereSQL)
	base := fmt.Sprintf("SELECT "+_widgetSQLCols+" FROM %s", s.qualified())
	var q string
	if whereSQL == "" {
		q = fmt.Sprintf(base+" ORDER BY "+_widgetOrderPK, s.qualified())
	} else {
		q = fmt.Sprintf(base+" WHERE %s ORDER BY "+_widgetOrderPK, whereSQL, s.qualified())
	}
	rows, err := s.pool.Query(ctx, q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*Widget
	for rows.Next() {
		v, err := scanWidgetRow(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

func (s *WidgetStore) Create(ctx context.Context, v *Widget) (string, error) {
	v.SetDeleted(false)
	var insVer int64
	if p := v.Version(); p != nil {
		insVer = *p
	}
	q := fmt.Sprintf("INSERT INTO %s ("+_widgetSQLCols+") VALUES ($1, $2, $3, $4)", s.qualified())
	_, err := s.pool.Exec(ctx, q, v.ID(), v.Title, insVer, v.Del)
	if err != nil {
		return "", err
	}
	return v.ID(), nil
}

func (s *WidgetStore) Update(ctx context.Context, v *Widget) (*Widget, error) {
	newVer := time.Now().UnixNano()
	q := fmt.Sprintf("UPDATE %s SET "+_widgetUpdateSet+" WHERE "+_widgetOrderPK+" = $1", s.qualified())
	ct, err := s.pool.Exec(ctx, q, v.ID(), v.Title, newVer, v.Del)
	if err != nil {
		return v, err
	}
	if ct.RowsAffected() == 0 {
		return v, postgres.ErrNotFound
	}
	return v, nil
}

func (s *WidgetStore) Delete(ctx context.Context, id string) error {
	q := fmt.Sprintf("DELETE FROM %s WHERE "+_widgetOrderPK+" = $1", s.qualified())
	ct, err := s.pool.Exec(ctx, q, id)
	if err != nil {
		return err
	}
	if ct.RowsAffected() == 0 {
		return postgres.ErrNotFound
	}
	return nil
}

func (s *WidgetStore) UpdateDoc(ctx context.Context, id string, set, unset map[string]any) (bool, error) {
	if len(set) == 0 && len(unset) == 0 {
		return false, postgres.ErrNothingToUpdate
	}
	row := s.pool.QueryRow(ctx, fmt.Sprintf("SELECT "+_widgetSQLCols+" FROM %s WHERE "+_widgetOrderPK+" = $1", s.qualified()), id)
	cur, err := scanWidgetRow(row)
	if err != nil {
		return false, err
	}
	touched := false
	for k, raw := range set {
		switch k {
		case "title":
			if s, ok := raw.(string); ok {
				cur.Title = &s
				touched = true
			}

		case "version":
			switch n := raw.(type) {
			case int64:
				cur.Ver = &n
				touched = true
			case int:
				x := int64(n)
				cur.Ver = &x
				touched = true
			case float64:
				x := int64(n)
				cur.Ver = &x
				touched = true
			}

		case "deleted":
			if b, ok := raw.(bool); ok {
				cur.Del = &b
				touched = true
			}

		default:
			// unknown key ignored
		}
	}
	for k := range unset {
		switch k {
		case "title":
			cur.Title = nil
			touched = true

		case "version":
			cur.Ver = nil
			touched = true

		case "deleted":
			cur.Del = nil
			touched = true

		default:
		}
	}
	if !touched {
		return false, postgres.ErrNothingToUpdate
	}

	newVer := time.Now().UnixNano()

	q := fmt.Sprintf("UPDATE %s SET "+_widgetUpdateSet+" WHERE "+_widgetOrderPK+" = $1", s.qualified())
	ct, err := s.pool.Exec(ctx, q, id, cur.Title, newVer, cur.Del)
	if err != nil {
		return false, err
	}
	return ct.RowsAffected() > 0, nil
}

func decodeWidgetTuple(m *pgtype.Map, rel *pglogrepl.RelationMessageV2, tuple *pglogrepl.TupleData) (*Widget, error) {
	if tuple == nil {
		return nil, nil
	}
	var v Widget
	{
		i := postgres.ColumnIndexByName(rel, "id")
		if i < 0 {
			return nil, fmt.Errorf("column %q missing in relation", "id")
		}
		col := postgres.TupleColumn(tuple, i)
		if col == nil {
			return nil, fmt.Errorf("tuple column %d missing", i)
		}
		oid, err := postgres.TupleColumnOID(rel, i)
		if err != nil {
			return nil, err
		}
		if err := postgres.DecodeText(m, oid, *col, &v.IDVal); err != nil {
			return nil, err
		}
	}
	{
		i := postgres.ColumnIndexByName(rel, "title")
		if i < 0 {
			return nil, fmt.Errorf("column %q missing in relation", "title")
		}
		col := postgres.TupleColumn(tuple, i)
		if col == nil {
			return nil, fmt.Errorf("tuple column %d missing", i)
		}
		oid, err := postgres.TupleColumnOID(rel, i)
		if err != nil {
			return nil, err
		}
		if err := postgres.DecodeTextPtr(m, oid, *col, &v.Title); err != nil {
			return nil, err
		}
	}
	{
		i := postgres.ColumnIndexByName(rel, "version")
		if i < 0 {
			return nil, fmt.Errorf("column %q missing in relation", "version")
		}
		col := postgres.TupleColumn(tuple, i)
		if col == nil {
			return nil, fmt.Errorf("tuple column %d missing", i)
		}
		oid, err := postgres.TupleColumnOID(rel, i)
		if err != nil {
			return nil, err
		}
		if err := postgres.DecodeInt8Ptr(m, oid, *col, &v.Ver); err != nil {
			return nil, err
		}
	}
	{
		i := postgres.ColumnIndexByName(rel, "deleted")
		if i < 0 {
			return nil, fmt.Errorf("column %q missing in relation", "deleted")
		}
		col := postgres.TupleColumn(tuple, i)
		if col == nil {
			return nil, fmt.Errorf("tuple column %d missing", i)
		}
		oid, err := postgres.TupleColumnOID(rel, i)
		if err != nil {
			return nil, err
		}
		if err := postgres.DecodeBoolPtr(m, oid, *col, &v.Del); err != nil {
			return nil, err
		}
	}
	return &v, nil
}

// WidgetTupleDecoder returns a [postgres.TupleDecoder] for logical replication (pgoutput).
func WidgetTupleDecoder() postgres.TupleDecoder[*Widget] {
	m := pgtype.NewMap()
	return func(rel *pglogrepl.RelationMessageV2, tuple *pglogrepl.TupleData) (*Widget, error) {
		return decodeWidgetTuple(m, rel, tuple)
	}
}

