package entitygen

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Generate writes goose SQL and a RowStore implementation for each type in cfg.Types.
func Generate(cfg Config) error {
	if cfg.Src == "" {
		return fmt.Errorf("entitygen: -src is required")
	}
	if len(cfg.Types) == 0 {
		return fmt.Errorf("entitygen: -types is required")
	}
	if cfg.Table == "" {
		return fmt.Errorf("entitygen: -table is required")
	}
	if cfg.OutDir == "" {
		cfg.OutDir = "."
	}
	pk := cfg.PK
	if pk == "" {
		pk = "id"
	}
	seq := cfg.Seq
	if seq == "" {
		seq = "00001"
	}
	if err := os.MkdirAll(filepath.Join(cfg.OutDir, "migrations"), 0o755); err != nil {
		return err
	}
	for _, tn := range cfg.Types {
		tn = strings.TrimSpace(tn)
		if tn == "" {
			continue
		}
		meta, err := ParseFile(cfg.Src, tn)
		if err != nil {
			return err
		}
		pkg := cfg.PkgName
		if pkg == "" {
			pkg = meta.Package
		}
		if !hasPK(meta.Fields, pk) {
			return fmt.Errorf("entitygen: no field maps to primary key column %q", pk)
		}
		goBody := genGo(pkg, pk, meta)
		goPath := filepath.Join(cfg.OutDir, storeFileName(tn))
		if err := os.WriteFile(goPath, []byte(goBody), 0o644); err != nil {
			return err
		}
		sqlBody := genSQL(cfg.Table, meta, pk)
		sqlPath := filepath.Join(cfg.OutDir, "migrations", fmt.Sprintf("%s_%s_init.up.sql", seq, cfg.Table))
		if err := os.WriteFile(sqlPath, []byte(sqlBody), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func hasPK(fields []Field, pk string) bool {
	for _, f := range fields {
		if f.Column == pk {
			return true
		}
	}
	return false
}

func storeFileName(typeName string) string {
	if typeName == "" {
		return "entity_store.go"
	}
	return strings.ToLower(typeName[:1]) + typeName[1:] + "_store.go"
}

func genSQL(table string, meta *ParsedEntity, pk string) string {
	var b strings.Builder
	b.WriteString("-- +goose Up\n")
	b.WriteString("-- +goose StatementBegin\n")
	b.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %q (\n", table))
	for i, f := range meta.Fields {
		line := fmt.Sprintf("  %q %s", f.Column, f.SQLType)
		if f.Column == pk {
			line += " PRIMARY KEY"
		}
		if f.Column == "version" && f.Kind == KindInt64 && !f.Nullable {
			line += " DEFAULT 0"
		}
		if i+1 < len(meta.Fields) {
			line += ","
		}
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString(");\n")
	b.WriteString(fmt.Sprintf("ALTER TABLE %q REPLICA IDENTITY FULL;\n", table))
	b.WriteString("-- +goose StatementEnd\n\n")
	b.WriteString("-- +goose Down\n")
	b.WriteString("-- +goose StatementBegin\n")
	b.WriteString("-- Additive policy: no DROP TABLE in default down (manual rollback if needed).\nSELECT 1;\n")
	b.WriteString("-- +goose StatementEnd\n")
	return b.String()
}

func goConstPrefix(typeName string) string {
	if typeName == "" {
		return "_entity"
	}
	return "_" + strings.ToLower(typeName[:1]) + typeName[1:]
}

func sqlColListIdent(meta *ParsedEntity) string {
	var p []string
	for _, f := range meta.Fields {
		p = append(p, fmt.Sprintf("\"%s\"", f.Column))
	}
	return strings.Join(p, ", ")
}

func sqlOrderPK(pk string) string {
	return fmt.Sprintf("\"%s\"", pk)
}

func sqlUpdateSet(meta *ParsedEntity, pk string) string {
	var sets []string
	argN := 2
	for _, f := range meta.Fields {
		if f.Column == pk {
			continue
		}
		sets = append(sets, fmt.Sprintf("\"%s\" = $%d", f.Column, argN))
		argN++
	}
	return strings.Join(sets, ", ")
}

func genConstBlock(typeName string, meta *ParsedEntity, pk string) string {
	pref := goConstPrefix(typeName)
	cols := strconv.Quote(sqlColListIdent(meta))
	orderPK := strconv.Quote(sqlOrderPK(pk))
	setAll := strconv.Quote(sqlUpdateSet(meta, pk))
	return fmt.Sprintf(`const (
	%sSQLCols = %s
	%sOrderPK = %s
	%sUpdateSet = %s
)

`, pref, cols, pref, orderPK, pref, setAll)
}

func genGo(pkg, pk string, meta *ParsedEntity) string {
	typeName := meta.TypeName
	var b strings.Builder
	b.WriteString("// Code generated by github.com/dhlab-tech/go-inmemory-platform/cmd/entitygen. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	b.WriteString(`import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/dhlab-tech/go-inmemory-platform/pkg/postgres"
	"github.com/jackc/pglogrepl"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

`)

	b.WriteString(genConstBlock(typeName, meta, pk))

	b.WriteString(fmt.Sprintf(`// %[1]sStore is a generated [postgres.RowStore] for %[1]s (typed columns; no reflection on query paths).
type %[1]sStore struct {
	pool   *pgxpool.Pool
	schema string
	table  string
}

// New%[1]sStore constructs a store. table is the logical table name (same as entity.Table in inmemory).
func New%[1]sStore(pool *pgxpool.Pool, schema, table string) *%[1]sStore {
	return &%[1]sStore{pool: pool, schema: schema, table: table}
}

func (s *%[1]sStore) qualified() string {
	return postgres.QualifiedTable(s.schema, s.table)
}

`, typeName))

	pref := goConstPrefix(typeName)
	b.WriteString(genScanFunc(typeName, meta))
	b.WriteString(genAll(typeName, pref))
	b.WriteString(genFind(typeName, pref))
	b.WriteString(genCreate(typeName, meta, pk, pref))
	b.WriteString(genUpdate(typeName, meta, pk, pref))
	b.WriteString(genDelete(typeName, pref))
	b.WriteString(genUpdateDoc(typeName, meta, pk, pref))
	b.WriteString(genTupleDecoder(typeName, meta))
	b.WriteString(genDecoderFn(typeName))
	return b.String()
}

func genScanFunc(typeName string, meta *ParsedEntity) string {
	var scanArgs []string
	for _, f := range meta.Fields {
		scanArgs = append(scanArgs, "&v."+f.GoName)
	}
	return fmt.Sprintf(`func scan%[1]sRow(row interface{ Scan(dest ...any) error }) (*%[1]s, error) {
	var v %[1]s
	if err := row.Scan(%[2]s); err != nil {
		return nil, err
	}
	return &v, nil
}

`, typeName, strings.Join(scanArgs, ", "))
}

func genAll(typeName, pref string) string {
	return fmt.Sprintf(`func (s *%[1]sStore) All(ctx context.Context) ([]*%[1]s, error) {
	q := fmt.Sprintf("SELECT "+%[2]sSQLCols+" FROM %%s ORDER BY "+%[2]sOrderPK, s.qualified())
	rows, err := s.pool.Query(ctx, q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*%[1]s
	for rows.Next() {
		v, err := scan%[1]sRow(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

`, typeName, pref)
}

func genFind(typeName, pref string) string {
	return fmt.Sprintf(`func (s *%[1]sStore) FindWithFilter(ctx context.Context, whereSQL string) ([]*%[1]s, error) {
	whereSQL = strings.TrimSpace(whereSQL)
	base := fmt.Sprintf("SELECT "+%[2]sSQLCols+" FROM %%s", s.qualified())
	var q string
	if whereSQL == "" {
		q = fmt.Sprintf(base+" ORDER BY "+%[2]sOrderPK, s.qualified())
	} else {
		q = fmt.Sprintf(base+" WHERE %%s ORDER BY "+%[2]sOrderPK, whereSQL, s.qualified())
	}
	rows, err := s.pool.Query(ctx, q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*%[1]s
	for rows.Next() {
		v, err := scan%[1]sRow(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

`, typeName, pref)
}

func genCreate(typeName string, meta *ParsedEntity, pk, pref string) string {
	var placeholders []string
	var args []string
	n := 1
	hasVerCol := false
	for _, f := range meta.Fields {
		if f.Column == "version" {
			hasVerCol = true
		}
	}
	for range meta.Fields {
		placeholders = append(placeholders, fmt.Sprintf("$%d", n))
		n++
	}
	for _, f := range meta.Fields {
		if f.Column == pk {
			args = append(args, "v.ID()")
			continue
		}
		if f.Column == "version" && hasVerCol {
			args = append(args, "insVer")
			continue
		}
		args = append(args, "v."+f.GoName)
	}
	prefix := ""
	if hasVerCol {
		prefix = `	var insVer int64
	if p := v.Version(); p != nil {
		insVer = *p
	}
`
	}
	return fmt.Sprintf(`func (s *%[1]sStore) Create(ctx context.Context, v *%[1]s) (string, error) {
	v.SetDeleted(false)
%[5]s	q := fmt.Sprintf("INSERT INTO %%s ("+%[2]sSQLCols+") VALUES (%[3]s)", s.qualified())
	_, err := s.pool.Exec(ctx, q, %[4]s)
	if err != nil {
		return "", err
	}
	return v.ID(), nil
}

`, typeName, pref, strings.Join(placeholders, ", "), strings.Join(args, ", "), prefix)
}

func genUpdate(typeName string, meta *ParsedEntity, pk, pref string) string {
	var args []string
	hasNonPK := false
	for _, f := range meta.Fields {
		if f.Column == pk {
			continue
		}
		hasNonPK = true
		if f.Column == "version" {
			args = append(args, "newVer")
		} else {
			args = append(args, "v."+f.GoName)
		}
	}
	if !hasNonPK {
		return fmt.Sprintf(`func (s *%[1]sStore) Update(ctx context.Context, v *%[1]s) (*%[1]s, error) {
	return v, nil
}

`, typeName)
	}
	return fmt.Sprintf(`func (s *%[1]sStore) Update(ctx context.Context, v *%[1]s) (*%[1]s, error) {
	newVer := time.Now().UnixNano()
	q := fmt.Sprintf("UPDATE %%s SET "+%[2]sUpdateSet+" WHERE "+%[2]sOrderPK+" = $1", s.qualified())
	ct, err := s.pool.Exec(ctx, q, v.ID(), %[3]s)
	if err != nil {
		return v, err
	}
	if ct.RowsAffected() == 0 {
		return v, postgres.ErrNotFound
	}
	return v, nil
}

`, typeName, pref, strings.Join(args, ", "))
}

func genDelete(typeName, pref string) string {
	return fmt.Sprintf(`func (s *%[1]sStore) Delete(ctx context.Context, id string) error {
	q := fmt.Sprintf("DELETE FROM %%s WHERE "+%[2]sOrderPK+" = $1", s.qualified())
	ct, err := s.pool.Exec(ctx, q, id)
	if err != nil {
		return err
	}
	if ct.RowsAffected() == 0 {
		return postgres.ErrNotFound
	}
	return nil
}

`, typeName, pref)
}

func genUpdateDoc(typeName string, meta *ParsedEntity, pk, pref string) string {
	var setCases, unsetCases strings.Builder
	for _, f := range meta.Fields {
		if f.Column == pk {
			continue
		}
		switch f.Kind {
		case KindString:
			if f.Nullable {
				setCases.WriteString(fmt.Sprintf(`
		case %[1]q:
			if s, ok := raw.(string); ok {
				cur.%[2]s = &s
				touched = true
			}
`, f.UpdateKey, f.GoName))
				unsetCases.WriteString(fmt.Sprintf(`
		case %[1]q:
			cur.%[2]s = nil
			touched = true
`, f.UpdateKey, f.GoName))
			} else {
				setCases.WriteString(fmt.Sprintf(`
		case %[1]q:
			if s, ok := raw.(string); ok {
				cur.%[2]s = s
				touched = true
			}
`, f.UpdateKey, f.GoName))
			}
		case KindInt64:
			if f.Nullable {
				setCases.WriteString(fmt.Sprintf(`
		case %[1]q:
			switch n := raw.(type) {
			case int64:
				cur.%[2]s = &n
				touched = true
			case int:
				x := int64(n)
				cur.%[2]s = &x
				touched = true
			case float64:
				x := int64(n)
				cur.%[2]s = &x
				touched = true
			}
`, f.UpdateKey, f.GoName))
				unsetCases.WriteString(fmt.Sprintf(`
		case %[1]q:
			cur.%[2]s = nil
			touched = true
`, f.UpdateKey, f.GoName))
			} else {
				setCases.WriteString(fmt.Sprintf(`
		case %[1]q:
			switch n := raw.(type) {
			case int64:
				cur.%[2]s = n
				touched = true
			case int:
				cur.%[2]s = int64(n)
				touched = true
			case float64:
				cur.%[2]s = int64(n)
				touched = true
			}
`, f.UpdateKey, f.GoName))
			}
		case KindBool:
			if f.Nullable {
				setCases.WriteString(fmt.Sprintf(`
		case %[1]q:
			if b, ok := raw.(bool); ok {
				cur.%[2]s = &b
				touched = true
			}
`, f.UpdateKey, f.GoName))
				unsetCases.WriteString(fmt.Sprintf(`
		case %[1]q:
			cur.%[2]s = nil
			touched = true
`, f.UpdateKey, f.GoName))
			} else {
				setCases.WriteString(fmt.Sprintf(`
		case %[1]q:
			if b, ok := raw.(bool); ok {
				cur.%[2]s = b
				touched = true
			}
`, f.UpdateKey, f.GoName))
			}
		}
	}

	hasVersion := false
	for _, f := range meta.Fields {
		if f.Column == "version" {
			hasVersion = true
			break
		}
	}
	verDecl := ""
	if hasVersion {
		verDecl = "\n\tnewVer := time.Now().UnixNano()\n"
	}

	execArgs := updateDocExecArgs(meta, pk)

	return fmt.Sprintf(`func (s *%[1]sStore) UpdateDoc(ctx context.Context, id string, set, unset map[string]any) (bool, error) {
	if len(set) == 0 && len(unset) == 0 {
		return false, postgres.ErrNothingToUpdate
	}
	row := s.pool.QueryRow(ctx, fmt.Sprintf("SELECT "+%[2]sSQLCols+" FROM %%s WHERE "+%[2]sOrderPK+" = $1", s.qualified()), id)
	cur, err := scan%[1]sRow(row)
	if err != nil {
		return false, err
	}
	touched := false
	for k, raw := range set {
		switch k {%[3]s
		default:
			// unknown key ignored
		}
	}
	for k := range unset {
		switch k {%[4]s
		default:
		}
	}
	if !touched {
		return false, postgres.ErrNothingToUpdate
	}
%[5]s
	q := fmt.Sprintf("UPDATE %%s SET "+%[2]sUpdateSet+" WHERE "+%[2]sOrderPK+" = $1", s.qualified())
	ct, err := s.pool.Exec(ctx, q, %[6]s)
	if err != nil {
		return false, err
	}
	return ct.RowsAffected() > 0, nil
}

`, typeName, pref, setCases.String(), unsetCases.String(), verDecl, execArgs)
}

func updateDocExecArgs(meta *ParsedEntity, pk string) string {
	var args []string
	args = append(args, "id")
	for _, f := range meta.Fields {
		if f.Column == pk {
			continue
		}
		if f.Column == "version" {
			args = append(args, "newVer")
			continue
		}
		args = append(args, "cur."+f.GoName)
	}
	return strings.Join(args, ", ")
}

func genTupleDecoder(typeName string, meta *ParsedEntity) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("func decode%sTuple(m *pgtype.Map, rel *pglogrepl.RelationMessageV2, tuple *pglogrepl.TupleData) (*%s, error) {\n", typeName, typeName))
	b.WriteString("\tif tuple == nil {\n\t\treturn nil, nil\n\t}\n")
	b.WriteString(fmt.Sprintf("\tvar v %s\n", typeName))
	for _, f := range meta.Fields {
		b.WriteString("\t{\n")
		b.WriteString(fmt.Sprintf("\t\ti := postgres.ColumnIndexByName(rel, %q)\n", f.Column))
		b.WriteString("\t\tif i < 0 {\n")
		b.WriteString(fmt.Sprintf("\t\t\treturn nil, fmt.Errorf(\"column %%q missing in relation\", %q)\n", f.Column))
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tcol := postgres.TupleColumn(tuple, i)\n")
		b.WriteString("\t\tif col == nil {\n")
		b.WriteString("\t\t\treturn nil, fmt.Errorf(\"tuple column %d missing\", i)\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\toid, err := postgres.TupleColumnOID(rel, i)\n")
		b.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		switch f.Kind {
		case KindString:
			if f.Nullable {
				b.WriteString(fmt.Sprintf("\t\tif err := postgres.DecodeTextPtr(m, oid, *col, &v.%s); err != nil {\n\t\t\treturn nil, err\n\t\t}\n", f.GoName))
			} else {
				b.WriteString(fmt.Sprintf("\t\tif err := postgres.DecodeText(m, oid, *col, &v.%s); err != nil {\n\t\t\treturn nil, err\n\t\t}\n", f.GoName))
			}
		case KindInt64:
			if f.Nullable {
				b.WriteString(fmt.Sprintf("\t\tif err := postgres.DecodeInt8Ptr(m, oid, *col, &v.%s); err != nil {\n\t\t\treturn nil, err\n\t\t}\n", f.GoName))
			} else {
				b.WriteString(fmt.Sprintf("\t\tif err := postgres.DecodeInt8(m, oid, *col, &v.%s); err != nil {\n\t\t\treturn nil, err\n\t\t}\n", f.GoName))
			}
		case KindBool:
			if f.Nullable {
				b.WriteString(fmt.Sprintf("\t\tif err := postgres.DecodeBoolPtr(m, oid, *col, &v.%s); err != nil {\n\t\t\treturn nil, err\n\t\t}\n", f.GoName))
			} else {
				b.WriteString(fmt.Sprintf("\t\tif err := postgres.DecodeBool(m, oid, *col, &v.%s); err != nil {\n\t\t\treturn nil, err\n\t\t}\n", f.GoName))
			}
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn &v, nil\n}\n\n")
	return b.String()
}

func genDecoderFn(typeName string) string {
	return fmt.Sprintf(`// %[1]sTupleDecoder returns a [postgres.TupleDecoder] for logical replication (pgoutput).
func %[1]sTupleDecoder() postgres.TupleDecoder[*%[1]s] {
	m := pgtype.NewMap()
	return func(rel *pglogrepl.RelationMessageV2, tuple *pglogrepl.TupleData) (*%[1]s, error) {
		return decode%[1]sTuple(m, rel, tuple)
	}
}

`, typeName)
}
